// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/eko/gocache/cache"
	"sme-jwk/internal/domain/base"
	"sme-jwk/internal/domain/jwk"
)

// Injectors from wire.go:

// InitBaseAPI init base api wire
func InitBaseAPI() base.API {
	service := base.ProvideService()
	api := base.ProvideAPI(service)
	return api
}

// InitJWKAPI init jwk api wire
func InitJWKAPI(chaincache *cache.ChainCache) jwk.API {
	service := jwk.ProvideService(chaincache)
	api := jwk.ProvideAPI(service)
	return api
}
